# Site settings
title: Psallite
email: psallite@thedancingmaster.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://psallitemusic.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#deployment
host: 0.0.0.0
