version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec jekyll serve --force_polling --watch

volumes:
  gem_cache:
