name: Run CI

on: 
  push:
    branches:
      - main

jobs:
  # Run tests
  build_site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Set up gem caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle 
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: build jekyll
        run: bundle exec jekyll build
      - name: copy files to production
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "./_site/*"
          rm: true
          target: ${{ secrets.REMOTE_DIR }}
          strip_components: 1

